### ISSUE TITLE
Naming

### ISSUE THREAD

**Issue by chrisblammo123** [Team2470/FRC-2019#4]
**What is being affected**
Names for functions, variables, classes, and enumerations.

**How is it being changed**
Change them to be more consistent:
- Functions and variables are camel case.
- Classes and enumerations are pascal case.

**Additional context**
No other context needed.

**Comment by Ethan-Bierlein** [comment]
Style reformatting is mostly done; there may be a few places here and there that I missed in my walk through the codebase, but they can be fixed on an individual case-by-case basis. I also took the liberty of going through and removing all the `m_` prefixes on names; they were applied inconsistently, and often not to only member variables. Prefer the use of `this->` in the future if you _must_ explicitly indicate that you are referencing a member variable.
